### ISSUE TITLE
Display extra fields stored in "other_tags"

### ISSUE THREAD

**Issue by agila5** [ITSLeeds/osmextract#107]
I think it could be a good idea creating a function for displaying the extra fields stored in the column "other_tags". For example here: 

``` r
library(sf)
osmextract::oe_get("Andorra")[9]
other_tags
#> 1   "maxspeed"=>"30","old_ref"=>"N 22","oneway"=>"yes","ref"=>"N 22"
#> 3   "maxspeed"=>"30","old_ref"=>"CG-2","oneway"=>"yes","ref"=>"CG-2"
#> 4   "junction"=>"roundabout","ref"=>"CG-2"
#> 5   "maxspeed"=>"30","old_ref"=>"CG-2","oneway"=>"yes","ref"=>"CG-2"
#> 6   "maxspeed"=>"30","old_ref"=>"CG-2","oneway"=>"yes","ref"=>"CG-2"
```
it should say that the extra fields are called "maxspeed", "old_ref", "oneway", "ref" and "junction". This is useful for specifying the extra attributes. 

I'm thinking about some sort of regex but any suggestion is welcome.

**Comment by Robinlovelace** [comment]
Definitely worth doing. I wonder if there's a way of doing it via SQL also...

**Comment by agila5** [comment]
The "other_tags" field is written using the `hstore` format which is described [here](https://www.postgresql.org/docs/current/hstore.html). 

In Table F-8 they describe several hstore functions and I would like to apply `akeys` and `avals`. The problem now is that I don't know how to apply these functions to a .gpkg file.

**Comment by agila5** [comment]
A few more details (for myself and future reference). There exists a function in SQLite dialect for working with hstore values: 

``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1

test_sf <- st_sf(
  data.frame(x = "a => b, c => d"), 
  geometry = st_sfc(st_point(c(1, 1)))
)
st_write(test_sf, "test_sf.gpkg")
#> Writing layer `test_sf' to data source `test_sf.gpkg' using driver `GPKG'
#> Writing 1 features with 1 fields and geometry type Point.
st_read("test_sf.gpkg", quiet = TRUE)
#> Simple feature collection with 1 feature and 1 field
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 1 xmax: 1 ymax: 1
#> CRS:            NA
#>                x        geom
#> 1 a => b, c => d POINT (1 1)
st_read("test_sf.gpkg", quiet = TRUE, query = "select geom, hstore_get_value(x, 'a') AS x FROM test_sf")
#> Simple feature collection with 1 feature and 1 field
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 1 xmax: 1 ymax: 1
#> CRS:            NA
#>   x        geom
#> 1 b POINT (1 1)
```

<sup>Created on 2020-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The problem is that, AFAIK, it's not possible to read all keys or all values but just the values associated to one particular key. The code behind `hstore_get_value()` is reported [here](https://github.com/OSGeo/gdal/blob/57d6107fc357988a95a062ae3b276f471bfcf2ea/gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp#L6705-L6728) and [here](https://github.com/OSGeo/gdal/blob/a499c8a602330340740f2bc1b158bfea330dcab4/gdal/ogr/swq_op_general.cpp#L125-L277). Unfortunately, I don't understand all the C++ details but I think that the core idea behind that code is that the value corresponding to a particular key is determined by creating a loop over the text and skipping the characters `"`, `\`, ` `, `=`, `>` and `,`. So, the idea behind the following regex is exactly the same: I exclude the same characters and I take the odd/even values representing key/value. Far from being perfect or extremely efficient but it seems to be working: 

``` r
# packages
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library(osmextract)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
#> Geofabrik data are taken from https://download.geofabrik.de/
#> For usage details of bbbike data see https://download.bbbike.org/osm/

# data
andorra <- oe_get("Andorra", query = "select other_tags, geometry from lines")

# Show 3 examples at random
set.seed(1)
(my_text <- as.character(andorra[["other_tags"]][sample(1:5995, 3)]))
#> [1] "\"bridge\"=>\"yes\",\"layer\"=>\"1\""                                                                                                                                                                                                                                                                                                                                    
#> [2] "\"admin_level\"=>\"2\",\"border_type\"=>\"nation\",\"boundary\"=>\"administrative\",\"name:ca\"=>\"França - Andorra\",\"name:en\"=>\"France - Andorra\",\"name:es\"=>\"Francia - Andorra\",\"name:fr\"=>\"France - Andorre\",\"name:lt\"=>\"Prancuzija - Andora\",\"name:oc\"=>\"França - Andòrra\",\"name:pt\"=>\"França - Andorra\",\"name:ru\"=>\"<U+0424><U+0440><U+0430><U+043D><U+0446><U+0438><U+044F> - <U+0410><U+043D><U+0434><U+043E><U+0440><U+0440><U+0430>\""
#> [3] "\"bridge\"=>\"yes\",\"layer\"=>\"1\",\"oneway\"=>\"yes\""

# Create regex
osm_matches <- gregexpr(pattern = '[^\"=>,\\]+', my_text)
key_value_matches <- regmatches(my_text, osm_matches)

# keys 
lapply(key_value_matches, function(x) x[seq(1, length(x), by = 2)])
#> [[1]]
#> [1] "bridge" "layer" 
#> 
#> [[2]]
#>  [1] "admin_level" "border_type" "boundary"    "name:ca"     "name:en"    
#>  [6] "name:es"     "name:fr"     "name:lt"     "name:oc"     "name:pt"    
#> [11] "name:ru"    
#> 
#> [[3]]
#> [1] "bridge" "layer"  "oneway"

# values
lapply(key_value_matches, function(x) x[seq(2, length(x), by = 2)])
#> [[1]]
#> [1] "yes" "1"  
#> 
#> [[2]]
#>  [1] "2"                   "nation"              "administrative"     
#>  [4] "França - Andorra"    "France - Andorra"    "Francia - Andorra"  
#>  [7] "France - Andorre"    "Prancuzija - Andora" "França - Andòrra"   
#> [10] "França - Andorra"    "<U+0424><U+0440><U+0430><U+043D><U+0446><U+0438><U+044F> - <U+0410><U+043D><U+0434><U+043E><U+0440><U+0440><U+0430>"
#> 
#> [[3]]
#> [1] "yes" "1"   "yes"
```

<sup>Created on 2020-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
A suitable question for StackExchange/RStudio Community or similar? I suspect so!

**Comment by Robinlovelace** [comment]
I'm sure 'good old fashioned' regex can extract the keys, but not sure how. The regexplain package may help there... https://github.com/gadenbuie/regexplain

**Comment by Robinlovelace** [comment]
Update @agila5, I think this solution you outlined above is as good as we need via good old regex, seems pretty fast too so I suggest implementing this, e.g. with a function like `oe_get_keys()`. Sound reasonable for a function name?

```r
lapply(key_value_matches, function(x) x[seq(1, length(x), by = 2)])
#> [[1]]
#> [1] "bridge" "layer" 
#> 
#> [[2]]
#>  [1] "admin_level" "border_type" "boundary"    "name:ca"     "name:en"    
#>  [6] "name:es"     "name:fr"     "name:lt"     "name:oc"     "name:pt"    
#> [11] "name:ru"    
#> 
#> [[3]]
#> [1] "bridge" "layer"  "oneway"
```

Amazing work on the regex :fire:

**Comment by agila5** [comment]
> Update @agila5, I think this solution you outlined above is as good as we need via good old regex, seems pretty fast too so I suggest implementing this, e.g. with a function like oe_get_keys(). Sound reasonable for a function name?

👍 I will create a PR to the vectortranslate repo in the evening

> Amazing work on the regex 🔥

Thanks!

**Comment by agila5** [comment]
@Robinlovelace One question: the parameter `extra_attributes` in `oe_vectortranslate` is used to specify which tags (i.e. key/value pairs) should be added to the GPKG file. I think a better name could be `extra_tags`, what do you think?

**Comment by Robinlovelace** [comment]
I think that it makes sense to change the name of the argument from `extra_attributes` to `extra_tags`. From an R perspective the argument adds extra columns (attributes) to the data frame but using OSM terminology is important. Plus `extra_tags` is concise.
