### ISSUE TITLE
Fix warnings in testthat 

### ISSUE THREAD

**Issue by agila5** [ITSLeeds/osmextract#111]

**Comment by agila5** [comment]
The warnings are: 
```
test-match.R:35: warning: oe_match: sfc_POINT objects
st_centroid does not give correct centroids for longitude/latitude data

test-match.R:36: warning: oe_match: sfc_POINT objects
st_centroid does not give correct centroids for longitude/latitude data

test-match.R:36: warning: oe_match: sfc_POINT objects
st_centroid does not give correct centroids for longitude/latitude data
```
and I think they will be fixed with the next version of `sf`

**Comment by Robinlovelace** [comment]
All the more reason for #103

**Comment by Robinlovelace** [comment]
We could also suppress warning messages.

**Comment by agila5** [comment]
> We could also suppress warning messages.

IMO the best option is to document that there may be some warning messages with spatial matching operations and not suppress warning messages. Then, as soon I can check and understand the new s2 stuff, I will take a look at #103 again

**Comment by Robinlovelace** [comment]
Sounds reasonable.
