### ISSUE TITLE
Add a new provider and show an update commit example

### ISSUE THREAD

**Issue by agila5** [ITSLeeds/osmextract#116]
For "new provider" vignette

**Comment by Robinlovelace** [comment]
Great work! Suggest also adding a map - that's probably covered in #127.

**Comment by Robinlovelace** [comment]
A map here... https://itsleeds.github.io/osmextract/articles/osmextract.html#oe_providerslist-providers

**Comment by agila5** [comment]
> Great work! Suggest also adding a map - that's probably covered in #127.

Yes, I'm working on a new vignette right now!
