### ISSUE TITLE
Add Ordnance Survey as a provider

### ISSUE THREAD

**Issue by agila5** [ITSLeeds/osmextract#130]
I'm not sure that this is a good idea (and I didn't check the licenses and so on), but I think the following links could be a starting point: 

- https://osdatahub.os.uk/docs/downloads/overview
- https://osdatahub.os.uk/docs/wfs/overview

**Comment by Robinlovelace** [comment]
I think that could be mission creep. This issue may be better placed here (although that package was developed just to read a specific type of OS data): https://github.com/ITSLeeds/mastermapr

**Comment by Robinlovelace** [comment]
Fully agree that code to access OS data products is needed. I just doubt that this repo is the best place for it. For a moment I wondered if OS had started republishing OSM data, which would be awesome (I'm trying to help bridge the gap between OS and OSM datasets, it's a big one).

**Comment by agila5** [comment]
> I think that could be mission creep. This issue may be better placed here (although that package was developed just to read a specific type of OS data): https://github.com/ITSLeeds/mastermapr

Ok, thanks! If (and when) I will try to work on a small prototype for integrating OS data I will open a new issue in that git repo. I leave this issue open just as a remainder.
