### ISSUE TITLE
Check if input "looks like" a URL

### ISSUE THREAD

**Issue by agila5** [ITSLeeds/osmextract#134]
The current approach in `oe_read` is to check if the input `file_path` points to an existing file, otherwise it assumes that it is a URL: 

https://github.com/ITSLeeds/osmextract/blob/1655ab4186c9a1402584234c3a9e808659940044/R/read.R#L69-L93

The problem, here, is that I think it is very easy to raise a (not-so-informative) error if the input `file_path` points to a non-existing file: 

``` r
library(osmextract)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright.
#> Any product made from OpenStreetMap must cite OSM as the data source.
#> Geofabrik data are taken from https://download.geofabrik.de/
#> For usage details of bbbike data see https://download.bbbike.org/osm/
#> OpenStreetMap_fr data are taken from http://download.openstreetmap.fr/
oe_read("geofabrik_typo-in-path.osm.pbf")
#> Error in utils::download.file(url = file_url, destfile = file_path, mode = "wb", : scheme not supported in URL 'geofabrik_typo-in-path.osm.pbf'
```

<sup>Created on 2020-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So I was thinking of adding a new `if` clause in `oe_read` to check if the input `file_path` "looks like" a URL (maybe with a [regex](https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url)). What do you think is the best approach here?

**Comment by Robinlovelace** [comment]
I think this is a great idea. It should be fairly simple to check if a char string is a URL, e.g. contains `http`, I imagine.

**Comment by agila5** [comment]
Self note: Check the R code in https://github.com/jimhester/urlchecker if, for whatever reason, the code in that PR doesn't work
