### ISSUE TITLE
Rethink the quiet = FALSE parameter

### ISSUE THREAD

**Issue by agila5** [ITSLeeds/osmextract#146]
See the discussion in https://github.com/ITSLeeds/osmextract/issues/143

**Comment by agila5** [comment]
Hi @Robinlovelace, I thought about this, and I think that we should set `quiet = FALSE` since 1) it's the same default value as in `sf::st_read`; 2) it's easy for a new user to miss that argument and 3) it's easier to set `quiet = TRUE` when you know that everything is working smoothly than `quiet = FALSE` when you are not sure if the function is working or not. 

What do you think?

**Comment by Robinlovelace** [comment]
Agreed, especially now the package is at an early stage and many people will be using it for the first time wondering what it's doing under the hood. :+1:
