### ISSUE TITLE
CI badge

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/osmextract#149]
In the readme does not look great... No idea what's causing this. Woops!

![image](https://user-images.githubusercontent.com/1825120/98710157-31e56980-237b-11eb-8805-56d7d8ba1ac4.png)

**Comment by agila5** [comment]
Hi Robin! Yes, I noticed that but I think that the GHA error is unrelated with the CI badge (see, for example, https://github.com/ITSLeeds/osmextract/runs/1381563932 which is run without any extra badge). 

It seems to be a problem with the CRAN pkg [textshaping](https://cran.r-project.org/web/packages/textshaping/index.html), which is a dependency of [ragg](https://github.com/r-lib/ragg), which is also a dependency of [pkgdown](https://cran.r-project.org/web/packages/pkgdown/index.html). I have no idea why it's failing but I will open a new issue in a few days if it's still not working.

**Comment by agila5** [comment]
I don't know why it was failing, I don't know why it's working now but I think we can close this!
