### ISSUE TITLE
Search for place location if there's no match in the providers

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/osmextract#154]
Reproducible example:

``` r
osmextract::oe_get("leeds")
#> No exact matching found for place = leeds. Best match is Laos.
#> Error: String distance between best match and the input place is 3, while the maximum threshold distance is equal to 1. You should increase the max_string_dist parameter, look for a closer match in the chosen provider database or consider using a different match_by variable.
```

<sup>Created on 2020-12-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Motivation: useful observation from reviewer https://github.com/ropensci/software-review/issues/395#issuecomment-746784728

> For example, the very first thing I tried was to look for a city I know, as I think most users will do:

**Comment by agila5** [comment]
![es](https://user-images.githubusercontent.com/22221146/104240598-9d6fb400-545c-11eb-93b5-3563908ff4af.png)

**Comment by agila5** [comment]
![Rplot2](https://user-images.githubusercontent.com/22221146/104241581-32bf7800-545e-11eb-896b-3f535dd1af5e.png)

**Comment by agila5** [comment]
![Rplot3](https://user-images.githubusercontent.com/22221146/104243054-4966ce80-5460-11eb-951b-ca1ce9d09f33.png)
