### ISSUE TITLE
Check for existing attributes

### ISSUE THREAD

**Issue by agila5** [ITSLeeds/osmextract#80]
The vectortranslate operation is expensive so I would add a check here

https://github.com/ITSLeeds/osmextractr/blob/6c0ab50aeecff02cb3b96b26a71f5c0c8b6bc11a/R/get.R#L110-L112

to check if the input `extra_attributes` are already present in the `.gpkg` file (maybe with ogrinfo -fields=YES) and, in that case, set `force_vectortranslate = FALSE`

**Comment by Robinlovelace** [comment]
Sounds good to me :+1:

**Comment by agila5** [comment]
Do you know if it's possible to read the names of the fields in a file using `sf` and without reading the file? Something like: 
``` r
system("ogrinfo -so filename.gpkg lines")
```

**Comment by Robinlovelace** [comment]
Not sure but it sure would be useful. A reasonable feature request for the `sf` issue tracker I think.

**Comment by agila5** [comment]
Solution: https://gis.stackexchange.com/questions/368201/extract-fields-names-in-r-without-reading-the-file 

Thanks @barryrowlingson

**Comment by barryrowlingson** [comment]
If you think I've done enough to deserve it, yes thank you!

**Comment by Robinlovelace** [comment]
See #82
