### ISSUE TITLE
Name II

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/osmextract#84]
Linking to #32 I think `osmextract` would be better than `osmextractr`. Not much in it other than `r` but it's jumped into my head a few times so thought I'd put it down as an issue before this gets submitted. Thoughts @agila5 ?

**Comment by agila5** [comment]
Honestly, I'm fine with both choices. I would just wait a couple of days and then if you still think that `osmextract` would be better then we can change the name.

**Comment by agila5** [comment]
I reopen since we need to change the urls of the test file after you change the repository name

**Comment by Robinlovelace** [comment]
GitHub repo now renamed.
