### ISSUE TITLE
Introductory vignette

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/osmextract#96]

**Comment by agila5** [comment]
I reopen as a remainder to finish the vignette after docs and tests

**Comment by Robinlovelace** [comment]
It's already looking good to me on the website: https://itsleeds.github.io/osmextract/articles/osmextract.html


![image](https://user-images.githubusercontent.com/1825120/89024562-35e60200-d31d-11ea-9908-a71b2eddbe9b.png)

Note, I'm using the ITS Leeds extract to reduce building and testing times, want to keep the CI tests to below 5 min if poss.

**Comment by agila5** [comment]
> Note, I'm using the ITS Leeds extract to reduce building and testing times, want to keep the CI tests to below 5 min if poss.

👍
