### ISSUE TITLE
Error with spatial match and bbbike

### ISSUE THREAD

**Issue by agila5** [ITSLeeds/osmextract#98]
``` r
library(osmextract)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
#> Geofabrik data are taken from https://download.geofabrik.de/
#> For usage details of bbbike data see https://download.bbbike.org/osm/

leeds = sf::st_sfc(sf::st_point(c(430147.8, 433551.5)), crs = 27700)
oe_match(leeds) # works
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
#> $url
#> [1] "https://download.geofabrik.de/europe/great-britain/england-latest.osm.pbf"
#> 
#> $file_size
#> [1] 928457533
oe_match(leeds, provider = "bbbike") # error
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
#> Error in oe_match.sfc_POINT(leeds, provider = "bbbike"): object 'smallest_zone' not found
```

<sup>Created on 2020-07-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The point is that the spatial matching is performed through a column called "level" and we must be sure that this column exists in the provider's database. `geofabrik` presents concentric areas with different "levels" (West Yorkshire lies within England which lies within Greate Britain which should lie within Europe) while these ideas are not clearly defined for bbbike

**Comment by agila5** [comment]
The problem is that with bbbike there are several overlapping areas: 

``` r
library(osmextract)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
#> Geofabrik data are taken from https://download.geofabrik.de/
#> For usage details of bbbike data see https://download.bbbike.org/osm/
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library(tmap)
tmap_mode("view")
#> tmap mode set to interactive viewing

tm_shape(bbbike_zones[c(1, 117, 135, 148), ]) + 
  tm_polygons(col = "lightgrey", alpha = 0.5)
```

![](https://i.imgur.com/g1Jb2CZ.png)

``` r
tm_shape(bbbike_zones[c(6, 65, 223), ]) + 
  tm_polygons(col = "lightgrey", alpha = 0.5)
```

![](https://i.imgur.com/6P2Uw1P.png)

``` r
tm_shape(bbbike_zones[c(22, 32, 82, 160, 177, 210, 22, 226), ]) + 
  tm_polygons(col = "lightgrey", alpha = 0.5)
```

![](https://i.imgur.com/eR8QYAW.png)

<sup>Created on 2020-07-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


What is a meaningful default when a point lies in an area shared between two or more cities? Choose using the nearest centroid?

**Comment by Robinlovelace** [comment]
Another thought: we should visualise the distribution of the provider areas more, we had that in the previous README.
